/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallArtServicesRouteImport } from './routes/wall-art-services'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallArtServicesIndexRouteImport } from './routes/wall-art-services.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as WallArtServicesWoodCarvedWallArtRouteImport } from './routes/wall-art-services.wood-carved-wall-art'
import { Route as WallArtServicesStencilWallPaintingRouteImport } from './routes/wall-art-services.stencil-wall-painting'
import { Route as WallArtServicesMuralPaintingsRouteImport } from './routes/wall-art-services.mural-paintings'
import { Route as ServicesWallpaperRouteImport } from './routes/services.wallpaper'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as WallArtServicesHomeTvUnitRouteImport } from './routes/wall-art-services.home.tv-unit'
import { Route as WallArtServicesHomeStaircaseRouteImport } from './routes/wall-art-services.home.staircase'
import { Route as WallArtServicesHomeMasterBedroomRouteImport } from './routes/wall-art-services.home.master-bedroom'
import { Route as WallArtServicesHomeLivingRoomRouteImport } from './routes/wall-art-services.home.living-room'
import { Route as WallArtServicesHomeKidsRoomRouteImport } from './routes/wall-art-services.home.kids-room'
import { Route as WallArtServicesHomeGuestRoomRouteImport } from './routes/wall-art-services.home.guest-room'
import { Route as WallArtServicesHomeCeilingRouteImport } from './routes/wall-art-services.home.ceiling'
import { Route as WallArtServicesHomeBalconyRouteImport } from './routes/wall-art-services.home.balcony'
import { Route as WallArtServicesHome3dPaintingRouteImport } from './routes/wall-art-services.home.3d-painting'
import { Route as WallArtServicesCommercialShopsOfficesRouteImport } from './routes/wall-art-services.commercial.shops-offices'
import { Route as WallArtServicesCommercialSchoolCartoonRouteImport } from './routes/wall-art-services.commercial.school-cartoon'
import { Route as WallArtServicesCommercialHotelsRestaurantsRouteImport } from './routes/wall-art-services.commercial.hotels-restaurants'

const WallArtServicesRoute = WallArtServicesRouteImport.update({
  id: '/wall-art-services',
  path: '/wall-art-services',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallArtServicesIndexRoute = WallArtServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WallArtServicesRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const WallArtServicesWoodCarvedWallArtRoute =
  WallArtServicesWoodCarvedWallArtRouteImport.update({
    id: '/wood-carved-wall-art',
    path: '/wood-carved-wall-art',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesStencilWallPaintingRoute =
  WallArtServicesStencilWallPaintingRouteImport.update({
    id: '/stencil-wall-painting',
    path: '/stencil-wall-painting',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesMuralPaintingsRoute =
  WallArtServicesMuralPaintingsRouteImport.update({
    id: '/mural-paintings',
    path: '/mural-paintings',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const ServicesWallpaperRoute = ServicesWallpaperRouteImport.update({
  id: '/services/wallpaper',
  path: '/services/wallpaper',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const WallArtServicesHomeTvUnitRoute =
  WallArtServicesHomeTvUnitRouteImport.update({
    id: '/home/tv-unit',
    path: '/home/tv-unit',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeStaircaseRoute =
  WallArtServicesHomeStaircaseRouteImport.update({
    id: '/home/staircase',
    path: '/home/staircase',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeMasterBedroomRoute =
  WallArtServicesHomeMasterBedroomRouteImport.update({
    id: '/home/master-bedroom',
    path: '/home/master-bedroom',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeLivingRoomRoute =
  WallArtServicesHomeLivingRoomRouteImport.update({
    id: '/home/living-room',
    path: '/home/living-room',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeKidsRoomRoute =
  WallArtServicesHomeKidsRoomRouteImport.update({
    id: '/home/kids-room',
    path: '/home/kids-room',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeGuestRoomRoute =
  WallArtServicesHomeGuestRoomRouteImport.update({
    id: '/home/guest-room',
    path: '/home/guest-room',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeCeilingRoute =
  WallArtServicesHomeCeilingRouteImport.update({
    id: '/home/ceiling',
    path: '/home/ceiling',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHomeBalconyRoute =
  WallArtServicesHomeBalconyRouteImport.update({
    id: '/home/balcony',
    path: '/home/balcony',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesHome3dPaintingRoute =
  WallArtServicesHome3dPaintingRouteImport.update({
    id: '/home/3d-painting',
    path: '/home/3d-painting',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesCommercialShopsOfficesRoute =
  WallArtServicesCommercialShopsOfficesRouteImport.update({
    id: '/commercial/shops-offices',
    path: '/commercial/shops-offices',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesCommercialSchoolCartoonRoute =
  WallArtServicesCommercialSchoolCartoonRouteImport.update({
    id: '/commercial/school-cartoon',
    path: '/commercial/school-cartoon',
    getParentRoute: () => WallArtServicesRoute,
  } as any)
const WallArtServicesCommercialHotelsRestaurantsRoute =
  WallArtServicesCommercialHotelsRestaurantsRouteImport.update({
    id: '/commercial/hotels-restaurants',
    path: '/commercial/hotels-restaurants',
    getParentRoute: () => WallArtServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/videos': typeof VideosRoute
  '/wall-art-services': typeof WallArtServicesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/wallpaper': typeof ServicesWallpaperRoute
  '/wall-art-services/mural-paintings': typeof WallArtServicesMuralPaintingsRoute
  '/wall-art-services/stencil-wall-painting': typeof WallArtServicesStencilWallPaintingRoute
  '/wall-art-services/wood-carved-wall-art': typeof WallArtServicesWoodCarvedWallArtRoute
  '/blogs/': typeof BlogsIndexRoute
  '/wall-art-services/': typeof WallArtServicesIndexRoute
  '/wall-art-services/commercial/hotels-restaurants': typeof WallArtServicesCommercialHotelsRestaurantsRoute
  '/wall-art-services/commercial/school-cartoon': typeof WallArtServicesCommercialSchoolCartoonRoute
  '/wall-art-services/commercial/shops-offices': typeof WallArtServicesCommercialShopsOfficesRoute
  '/wall-art-services/home/3d-painting': typeof WallArtServicesHome3dPaintingRoute
  '/wall-art-services/home/balcony': typeof WallArtServicesHomeBalconyRoute
  '/wall-art-services/home/ceiling': typeof WallArtServicesHomeCeilingRoute
  '/wall-art-services/home/guest-room': typeof WallArtServicesHomeGuestRoomRoute
  '/wall-art-services/home/kids-room': typeof WallArtServicesHomeKidsRoomRoute
  '/wall-art-services/home/living-room': typeof WallArtServicesHomeLivingRoomRoute
  '/wall-art-services/home/master-bedroom': typeof WallArtServicesHomeMasterBedroomRoute
  '/wall-art-services/home/staircase': typeof WallArtServicesHomeStaircaseRoute
  '/wall-art-services/home/tv-unit': typeof WallArtServicesHomeTvUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/videos': typeof VideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/wallpaper': typeof ServicesWallpaperRoute
  '/wall-art-services/mural-paintings': typeof WallArtServicesMuralPaintingsRoute
  '/wall-art-services/stencil-wall-painting': typeof WallArtServicesStencilWallPaintingRoute
  '/wall-art-services/wood-carved-wall-art': typeof WallArtServicesWoodCarvedWallArtRoute
  '/blogs': typeof BlogsIndexRoute
  '/wall-art-services': typeof WallArtServicesIndexRoute
  '/wall-art-services/commercial/hotels-restaurants': typeof WallArtServicesCommercialHotelsRestaurantsRoute
  '/wall-art-services/commercial/school-cartoon': typeof WallArtServicesCommercialSchoolCartoonRoute
  '/wall-art-services/commercial/shops-offices': typeof WallArtServicesCommercialShopsOfficesRoute
  '/wall-art-services/home/3d-painting': typeof WallArtServicesHome3dPaintingRoute
  '/wall-art-services/home/balcony': typeof WallArtServicesHomeBalconyRoute
  '/wall-art-services/home/ceiling': typeof WallArtServicesHomeCeilingRoute
  '/wall-art-services/home/guest-room': typeof WallArtServicesHomeGuestRoomRoute
  '/wall-art-services/home/kids-room': typeof WallArtServicesHomeKidsRoomRoute
  '/wall-art-services/home/living-room': typeof WallArtServicesHomeLivingRoomRoute
  '/wall-art-services/home/master-bedroom': typeof WallArtServicesHomeMasterBedroomRoute
  '/wall-art-services/home/staircase': typeof WallArtServicesHomeStaircaseRoute
  '/wall-art-services/home/tv-unit': typeof WallArtServicesHomeTvUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/videos': typeof VideosRoute
  '/wall-art-services': typeof WallArtServicesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/wallpaper': typeof ServicesWallpaperRoute
  '/wall-art-services/mural-paintings': typeof WallArtServicesMuralPaintingsRoute
  '/wall-art-services/stencil-wall-painting': typeof WallArtServicesStencilWallPaintingRoute
  '/wall-art-services/wood-carved-wall-art': typeof WallArtServicesWoodCarvedWallArtRoute
  '/blogs/': typeof BlogsIndexRoute
  '/wall-art-services/': typeof WallArtServicesIndexRoute
  '/wall-art-services/commercial/hotels-restaurants': typeof WallArtServicesCommercialHotelsRestaurantsRoute
  '/wall-art-services/commercial/school-cartoon': typeof WallArtServicesCommercialSchoolCartoonRoute
  '/wall-art-services/commercial/shops-offices': typeof WallArtServicesCommercialShopsOfficesRoute
  '/wall-art-services/home/3d-painting': typeof WallArtServicesHome3dPaintingRoute
  '/wall-art-services/home/balcony': typeof WallArtServicesHomeBalconyRoute
  '/wall-art-services/home/ceiling': typeof WallArtServicesHomeCeilingRoute
  '/wall-art-services/home/guest-room': typeof WallArtServicesHomeGuestRoomRoute
  '/wall-art-services/home/kids-room': typeof WallArtServicesHomeKidsRoomRoute
  '/wall-art-services/home/living-room': typeof WallArtServicesHomeLivingRoomRoute
  '/wall-art-services/home/master-bedroom': typeof WallArtServicesHomeMasterBedroomRoute
  '/wall-art-services/home/staircase': typeof WallArtServicesHomeStaircaseRoute
  '/wall-art-services/home/tv-unit': typeof WallArtServicesHomeTvUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/videos'
    | '/wall-art-services'
    | '/blogs/$slug'
    | '/services/wallpaper'
    | '/wall-art-services/mural-paintings'
    | '/wall-art-services/stencil-wall-painting'
    | '/wall-art-services/wood-carved-wall-art'
    | '/blogs/'
    | '/wall-art-services/'
    | '/wall-art-services/commercial/hotels-restaurants'
    | '/wall-art-services/commercial/school-cartoon'
    | '/wall-art-services/commercial/shops-offices'
    | '/wall-art-services/home/3d-painting'
    | '/wall-art-services/home/balcony'
    | '/wall-art-services/home/ceiling'
    | '/wall-art-services/home/guest-room'
    | '/wall-art-services/home/kids-room'
    | '/wall-art-services/home/living-room'
    | '/wall-art-services/home/master-bedroom'
    | '/wall-art-services/home/staircase'
    | '/wall-art-services/home/tv-unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/videos'
    | '/blogs/$slug'
    | '/services/wallpaper'
    | '/wall-art-services/mural-paintings'
    | '/wall-art-services/stencil-wall-painting'
    | '/wall-art-services/wood-carved-wall-art'
    | '/blogs'
    | '/wall-art-services'
    | '/wall-art-services/commercial/hotels-restaurants'
    | '/wall-art-services/commercial/school-cartoon'
    | '/wall-art-services/commercial/shops-offices'
    | '/wall-art-services/home/3d-painting'
    | '/wall-art-services/home/balcony'
    | '/wall-art-services/home/ceiling'
    | '/wall-art-services/home/guest-room'
    | '/wall-art-services/home/kids-room'
    | '/wall-art-services/home/living-room'
    | '/wall-art-services/home/master-bedroom'
    | '/wall-art-services/home/staircase'
    | '/wall-art-services/home/tv-unit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/videos'
    | '/wall-art-services'
    | '/blogs/$slug'
    | '/services/wallpaper'
    | '/wall-art-services/mural-paintings'
    | '/wall-art-services/stencil-wall-painting'
    | '/wall-art-services/wood-carved-wall-art'
    | '/blogs/'
    | '/wall-art-services/'
    | '/wall-art-services/commercial/hotels-restaurants'
    | '/wall-art-services/commercial/school-cartoon'
    | '/wall-art-services/commercial/shops-offices'
    | '/wall-art-services/home/3d-painting'
    | '/wall-art-services/home/balcony'
    | '/wall-art-services/home/ceiling'
    | '/wall-art-services/home/guest-room'
    | '/wall-art-services/home/kids-room'
    | '/wall-art-services/home/living-room'
    | '/wall-art-services/home/master-bedroom'
    | '/wall-art-services/home/staircase'
    | '/wall-art-services/home/tv-unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  VideosRoute: typeof VideosRoute
  WallArtServicesRoute: typeof WallArtServicesRouteWithChildren
  ServicesWallpaperRoute: typeof ServicesWallpaperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall-art-services': {
      id: '/wall-art-services'
      path: '/wall-art-services'
      fullPath: '/wall-art-services'
      preLoaderRoute: typeof WallArtServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall-art-services/': {
      id: '/wall-art-services/'
      path: '/'
      fullPath: '/wall-art-services/'
      preLoaderRoute: typeof WallArtServicesIndexRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/wall-art-services/wood-carved-wall-art': {
      id: '/wall-art-services/wood-carved-wall-art'
      path: '/wood-carved-wall-art'
      fullPath: '/wall-art-services/wood-carved-wall-art'
      preLoaderRoute: typeof WallArtServicesWoodCarvedWallArtRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/stencil-wall-painting': {
      id: '/wall-art-services/stencil-wall-painting'
      path: '/stencil-wall-painting'
      fullPath: '/wall-art-services/stencil-wall-painting'
      preLoaderRoute: typeof WallArtServicesStencilWallPaintingRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/mural-paintings': {
      id: '/wall-art-services/mural-paintings'
      path: '/mural-paintings'
      fullPath: '/wall-art-services/mural-paintings'
      preLoaderRoute: typeof WallArtServicesMuralPaintingsRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/services/wallpaper': {
      id: '/services/wallpaper'
      path: '/services/wallpaper'
      fullPath: '/services/wallpaper'
      preLoaderRoute: typeof ServicesWallpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/wall-art-services/home/tv-unit': {
      id: '/wall-art-services/home/tv-unit'
      path: '/home/tv-unit'
      fullPath: '/wall-art-services/home/tv-unit'
      preLoaderRoute: typeof WallArtServicesHomeTvUnitRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/staircase': {
      id: '/wall-art-services/home/staircase'
      path: '/home/staircase'
      fullPath: '/wall-art-services/home/staircase'
      preLoaderRoute: typeof WallArtServicesHomeStaircaseRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/master-bedroom': {
      id: '/wall-art-services/home/master-bedroom'
      path: '/home/master-bedroom'
      fullPath: '/wall-art-services/home/master-bedroom'
      preLoaderRoute: typeof WallArtServicesHomeMasterBedroomRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/living-room': {
      id: '/wall-art-services/home/living-room'
      path: '/home/living-room'
      fullPath: '/wall-art-services/home/living-room'
      preLoaderRoute: typeof WallArtServicesHomeLivingRoomRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/kids-room': {
      id: '/wall-art-services/home/kids-room'
      path: '/home/kids-room'
      fullPath: '/wall-art-services/home/kids-room'
      preLoaderRoute: typeof WallArtServicesHomeKidsRoomRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/guest-room': {
      id: '/wall-art-services/home/guest-room'
      path: '/home/guest-room'
      fullPath: '/wall-art-services/home/guest-room'
      preLoaderRoute: typeof WallArtServicesHomeGuestRoomRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/ceiling': {
      id: '/wall-art-services/home/ceiling'
      path: '/home/ceiling'
      fullPath: '/wall-art-services/home/ceiling'
      preLoaderRoute: typeof WallArtServicesHomeCeilingRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/balcony': {
      id: '/wall-art-services/home/balcony'
      path: '/home/balcony'
      fullPath: '/wall-art-services/home/balcony'
      preLoaderRoute: typeof WallArtServicesHomeBalconyRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/home/3d-painting': {
      id: '/wall-art-services/home/3d-painting'
      path: '/home/3d-painting'
      fullPath: '/wall-art-services/home/3d-painting'
      preLoaderRoute: typeof WallArtServicesHome3dPaintingRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/commercial/shops-offices': {
      id: '/wall-art-services/commercial/shops-offices'
      path: '/commercial/shops-offices'
      fullPath: '/wall-art-services/commercial/shops-offices'
      preLoaderRoute: typeof WallArtServicesCommercialShopsOfficesRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/commercial/school-cartoon': {
      id: '/wall-art-services/commercial/school-cartoon'
      path: '/commercial/school-cartoon'
      fullPath: '/wall-art-services/commercial/school-cartoon'
      preLoaderRoute: typeof WallArtServicesCommercialSchoolCartoonRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
    '/wall-art-services/commercial/hotels-restaurants': {
      id: '/wall-art-services/commercial/hotels-restaurants'
      path: '/commercial/hotels-restaurants'
      fullPath: '/wall-art-services/commercial/hotels-restaurants'
      preLoaderRoute: typeof WallArtServicesCommercialHotelsRestaurantsRouteImport
      parentRoute: typeof WallArtServicesRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface WallArtServicesRouteChildren {
  WallArtServicesMuralPaintingsRoute: typeof WallArtServicesMuralPaintingsRoute
  WallArtServicesStencilWallPaintingRoute: typeof WallArtServicesStencilWallPaintingRoute
  WallArtServicesWoodCarvedWallArtRoute: typeof WallArtServicesWoodCarvedWallArtRoute
  WallArtServicesIndexRoute: typeof WallArtServicesIndexRoute
  WallArtServicesCommercialHotelsRestaurantsRoute: typeof WallArtServicesCommercialHotelsRestaurantsRoute
  WallArtServicesCommercialSchoolCartoonRoute: typeof WallArtServicesCommercialSchoolCartoonRoute
  WallArtServicesCommercialShopsOfficesRoute: typeof WallArtServicesCommercialShopsOfficesRoute
  WallArtServicesHome3dPaintingRoute: typeof WallArtServicesHome3dPaintingRoute
  WallArtServicesHomeBalconyRoute: typeof WallArtServicesHomeBalconyRoute
  WallArtServicesHomeCeilingRoute: typeof WallArtServicesHomeCeilingRoute
  WallArtServicesHomeGuestRoomRoute: typeof WallArtServicesHomeGuestRoomRoute
  WallArtServicesHomeKidsRoomRoute: typeof WallArtServicesHomeKidsRoomRoute
  WallArtServicesHomeLivingRoomRoute: typeof WallArtServicesHomeLivingRoomRoute
  WallArtServicesHomeMasterBedroomRoute: typeof WallArtServicesHomeMasterBedroomRoute
  WallArtServicesHomeStaircaseRoute: typeof WallArtServicesHomeStaircaseRoute
  WallArtServicesHomeTvUnitRoute: typeof WallArtServicesHomeTvUnitRoute
}

const WallArtServicesRouteChildren: WallArtServicesRouteChildren = {
  WallArtServicesMuralPaintingsRoute: WallArtServicesMuralPaintingsRoute,
  WallArtServicesStencilWallPaintingRoute:
    WallArtServicesStencilWallPaintingRoute,
  WallArtServicesWoodCarvedWallArtRoute: WallArtServicesWoodCarvedWallArtRoute,
  WallArtServicesIndexRoute: WallArtServicesIndexRoute,
  WallArtServicesCommercialHotelsRestaurantsRoute:
    WallArtServicesCommercialHotelsRestaurantsRoute,
  WallArtServicesCommercialSchoolCartoonRoute:
    WallArtServicesCommercialSchoolCartoonRoute,
  WallArtServicesCommercialShopsOfficesRoute:
    WallArtServicesCommercialShopsOfficesRoute,
  WallArtServicesHome3dPaintingRoute: WallArtServicesHome3dPaintingRoute,
  WallArtServicesHomeBalconyRoute: WallArtServicesHomeBalconyRoute,
  WallArtServicesHomeCeilingRoute: WallArtServicesHomeCeilingRoute,
  WallArtServicesHomeGuestRoomRoute: WallArtServicesHomeGuestRoomRoute,
  WallArtServicesHomeKidsRoomRoute: WallArtServicesHomeKidsRoomRoute,
  WallArtServicesHomeLivingRoomRoute: WallArtServicesHomeLivingRoomRoute,
  WallArtServicesHomeMasterBedroomRoute: WallArtServicesHomeMasterBedroomRoute,
  WallArtServicesHomeStaircaseRoute: WallArtServicesHomeStaircaseRoute,
  WallArtServicesHomeTvUnitRoute: WallArtServicesHomeTvUnitRoute,
}

const WallArtServicesRouteWithChildren = WallArtServicesRoute._addFileChildren(
  WallArtServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  VideosRoute: VideosRoute,
  WallArtServicesRoute: WallArtServicesRouteWithChildren,
  ServicesWallpaperRoute: ServicesWallpaperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
